### PR TITLE
FIX CHANGELOG.md

### PR DESCRIPTION
**Pull request by tzagim**
The link points to the original GitHub instead of this site.

Version 0.0.1 cannot be released after more advanced versions.

Thanks for maintaining this excellent app.

### CODE REVIEW

**Comment by Vinetos** [comment]
Hello !
Thanks for your MR but I really like to have "human readable" changelog instead of just some commit message.  
This way, tech and non-tech people can read changes with ease ! What are your thought on this ? One answer could be the release section holding the "easy human-readable" changelog

And, I was thinking of a way to keep the old changelog of YetAnotherCallBlocker. Maybe a link to the original repository may be enough

**Comment by tzagim** [comment]
Hi!
It seems to me that the log of changes as it appears now is understandable even to non-technical people, they understand the essence of the change that was made, although most likely not the way and the meaning of the change in the code.

Changes made before the fork are not relevant (treat it as an alpha version uploaded to Github), the link to the main repository of YetAnotherCallBlocker is enough.

Best regards

**Comment by Vinetos** [comment]
Hello!

Regarding this update, I have a question about the utility of the CHANGELOG.md file. Given that the app will be published in the releases section of GitHub, would it make more sense to track changes directly within that section instead? 
This approach could potentially allow us to eliminate the need for a separate changelog file altogether.  

Regards,

**Comment by tzagim** [comment]
f-droid knows how to read the change log from GitHub releases, if you don't intend to publish on other app market, it's probably not necessary to use the CHANGELOG.md file.

Best regards

**Pull request closed without merging**
