### PR TITLE
Fix some FDroid-Bot Suggestions

### PR DESCRIPTION
**Pull request by Penaz91**
On [Fdroid](https://gitlab.com/fdroid/rfp/-/issues/2694) the bot has been complaining about some minor issues with fastlane folders and the gradle configuration.

This should solve most of the suggestions that have arisen.

I also added the icon in the `en-US/images` folder inside fastlane metadata, as asked by Licaon_Kter at Fdroid.

### CODE REVIEW

**Review by Vinetos — APPROVED** [review]
Big thanks for this ! I did not take the time to do it last week !

**Review by Vinetos — COMMENTED** [review]
Can you add a line in the changelog ?
You may create a line with `UNREALED` version as is has not been published yet

**Review by Vinetos — CHANGES_REQUESTED** [review]
Big thanks for this ! I did not take the time to do it last week !

Can you add a line in the changelog ?
You may create a line with `UNREALED` version as is has not been published yet

**Comment by Penaz91** [comment]
> Big thanks for this ! I did not take the time to do it last week !
> 
> Can you add a line in the changelog ? You may create a line with `UNREALED` version as is has not been published yet

No worries!

I didn't notice there was a changelog file, edited as requested. I'm not that great with handling changelogs so maybe it's time for me to learn!

**Review by Vinetos — APPROVED** [review]

**Pull request merged**
